# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Brainly(object):
    def setupUi(self, Brainly):
        Brainly.setObjectName("Brainly")
        Brainly.resize(800, 513)
        self.centralwidget = QtWidgets.QWidget(Brainly)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(450, 310, 331, 171))
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(450, 280, 61, 21))
        self.label.setObjectName("label")

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 781, 231))
        self.textEdit.setObjectName("textEdit")

        # self.frame = QtWidgets.QFrame(self.centralwidget)
        # self.frame.setGeometry(QtCore.QRect(19, 309, 271, 171))
        # self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.frame.setObjectName("frame")

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(90, 130, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 70, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")

        Brainly.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Brainly)
        self.statusbar.setObjectName("statusbar")
        Brainly.setStatusBar(self.statusbar)

        self.retranslateUi(Brainly)
        QtCore.QMetaObject.connectSlotsByName(Brainly)

    def retranslateUi(self, Brainly):
        _translate = QtCore.QCoreApplication.translate
        Brainly.setWindowTitle(_translate("Brainly", "Brainly - A Vehicle with a brain"))
        self.label.setText(_translate("Brainly", "Logs"))
        self.pushButton_4.setText(_translate("Brainly", "PushButton"))
        self.pushButton_2.setText(_translate("Brainly", "PushButton"))
        self.pushButton_3.setText(_translate("Brainly", "PushButton"))
        self.pushButton.setText(_translate("Brainly", "PushButton"))

if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Brainly = QtWidgets.QMainWindow()
    ui = Ui_Brainly()
    ui.setupUi(Brainly)
    Brainly.show()
    sys.exit(app.exec_())
